#h2
spring.datasource.url: jdbc:h2:mem:h2db
spring.h2.console.enabled: true
spring.h2.console.settings.web-allow-others: true
spring.datasource.platform: h2
spring.datasource.username: yash
spring.datasource.password: yash@123
spring.allowed.resources: /h2-console/**
#spring.jpa.show-sql: true
spring.datasource.driverClassName: org.h2.Driver
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


# JWT Configuration
jwt.secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
jwt.expiration: 36000

app-config:
  simpleKey: "value"
  timeout : 5s     # working


